# Definition of QA pipeline at SonarSource


SQ_VERSION:
  - 4.5.7 
  - DEV
  - LTS
  - LATEST_RELEASE

JAVA_VERSION:
  - LATEST_RELEASE

JAVASCRIPT_VERSION:
  - LATEST_RELEASE

PHP_VERSION:
  - LATEST_RELEASE

PYTHON_VERSION:
  - LATEST_RELEASE

COBOL_VERSION:
  - LATEST_RELEASE

exclude:
  
