# Definition of QA pipeline at SonarSource


SQ_VERSION: 
  - DEV
  - LTS
  - LATEST_RELEASE

JAVA_VERSION:
  - 3.8 
  - LATEST_RELEASE

JAVASCRIPT_VERSION:
  - 2.9 
  - LATEST_RELEASE

PHP_VERSION:
  - 2.7 
  - LATEST_RELEASE

PYTHON_VERSION:
  - 1.5
  - LATEST_RELEASE

exclude:
  
