language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT SQ_VERSION=5.2
    - TARGET=IT SQ_VERSION=5.3
    - TARGET=IT SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    # for integration tests and analysis
    - $HOME/.sonar

notifications:
  email: false
